# Configuration file for Schneider ATV320 drive
# Description: Velocity Control only
vendor_id: 0x0800005a
product_id: 0x00000389
assign_activate: 0x0300  # DC Synch register
auto_fault_reset: false  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x6040, sub_index: 0x00, type: uint16, default: 0}  # Control word
      - {index: 0x6042, sub_index: 0x00, type: int16, command_interface: velocity, default: 0}  # Target velocity
tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a00
    channels:
      - {index: 0x6041, sub_index: 0x00, type: uint16}  # Status word
      - {index: 0x6044, sub_index: 0x00, type: int16, state_interface: velocity}  # Velocity actual value
