# Configuration file for Advantech AMAX-5056
# Description : 8-ch Sink-type Digital Output EtherCAT Slice IO Module
vendor_id: 0x000013FE
product_id: 0x00035056
rpdo:  # RxPDO
  - index: 0x1600
    channels:
      - {index: 0x3101, sub_index: 0x01, type: bool, mask: 1, command_interface: d_output.1}
      - {index: 0x3101, sub_index: 0x02, type: bool, mask: 2, command_interface: d_output.2}
      - {index: 0x3101, sub_index: 0x03, type: bool, mask: 4, command_interface: d_output.3}
      - {index: 0x3101, sub_index: 0x04, type: bool, mask: 8, command_interface: d_output.4}
      - {index: 0x3101, sub_index: 0x05, type: bool, mask: 16, command_interface: d_output.5}
      - {index: 0x3101, sub_index: 0x06, type: bool, mask: 32, command_interface: d_output.6}
      - {index: 0x3101, sub_index: 0x07, type: bool, mask: 64, command_interface: d_output.7}
      - {index: 0x3101, sub_index: 0x08, type: bool, mask: 128, command_interface: d_output.8}
sm:  # Sync Manager
  - {index: 0, type: output, pdo: rpdo, watchdog: enable}
