# Configuration file for Beckhoff EL2124
# Description : EtherCAT Terminal, 4-channel digital output, 5 V DC, 20 mA.
vendor_id: 0x00000002
product_id: 0x084c3052
rpdo:  # RxPDO
  - index: 0x1600
    channels:
      - {index: 0x7000, sub_index: 0x01, type: bool, mask: 1, command_interface: d_output.1}
  - index: 0x1601
    channels:
      - {index: 0x7010, sub_index: 0x01, type: bool, mask: 2, command_interface: d_output.2}
  - index: 0x1602
    channels:
      - {index: 0x7020, sub_index: 0x01, type: bool, mask: 4, command_interface: d_output.3}
  - index: 0x1603
    channels:
      - {index: 0x7030, sub_index: 0x01, type: bool, mask: 8, command_interface: d_output.4}
sm:  # Sync Manager
  - {index: 0, type: output, pdo: rpdo, watchdog: enable}
