# Configuration file for Beckhoff EL3104
# Description : EtherCAT Terminal, 4-channel analog input, voltage, ±10 V, 16 bit, differential.
vendor_id: 0x00000002
product_id: 0x0c203052
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
      - {index: 0x6000, sub_index: 0x01, type: bool}  # Underrange
      - {index: 0x6000, sub_index: 0x02, type: bool}  # Overrange
      - {index: 0x6000, sub_index: 0x03, type: bit2}  # Limit 1
      - {index: 0x6000, sub_index: 0x05, type: bit2}  # Limit 2
      - {index: 0x6000, sub_index: 0x07, type: bool}  # Error
      - {index: 0x0000, sub_index: 0x00, type: bool}  # Gap
      - {index: 0x0000, sub_index: 0x00, type: bit5}  # Gap
      - {index: 0x6000, sub_index: 0x0e, type: bool}  # Sync error
      - {index: 0x6000, sub_index: 0x0f, type: bool}  # TxPDO State
      - {index: 0x6000, sub_index: 0x10, type: bool}  # TxPDO Toggle
      - {index: 0x6000, sub_index: 0x11, type: int16, state_interface: analog_input.1, factor: 0.000305185}  # Value
  - index: 0x1a02
    channels:
      - {index: 0x6010, sub_index: 0x01, type: bool}  # Underrange
      - {index: 0x6010, sub_index: 0x02, type: bool}  # Overrange
      - {index: 0x6010, sub_index: 0x03, type: bit2}  # Limit 1
      - {index: 0x6010, sub_index: 0x05, type: bit2}  # Limit 2
      - {index: 0x6010, sub_index: 0x07, type: bool}  # Error
      - {index: 0x0000, sub_index: 0x00, type: bool}  # Gap
      - {index: 0x0000, sub_index: 0x00, type: bit5}  # Gap
      - {index: 0x6010, sub_index: 0x0e, type: bool}  # Sync error
      - {index: 0x6010, sub_index: 0x0f, type: bool}  # TxPDO State
      - {index: 0x6010, sub_index: 0x10, type: bool}  # TxPDO Toggle
      - {index: 0x6010, sub_index: 0x11, type: int16, state_interface: analog_input.2, factor: 0.000305185}
  - index: 0x1a04
    channels:
      - {index: 0x6020, sub_index: 0x01, type: bool}  # Underrange
      - {index: 0x6020, sub_index: 0x02, type: bool}  # Overrange
      - {index: 0x6020, sub_index: 0x03, type: bit2}  # Limit 1
      - {index: 0x6020, sub_index: 0x05, type: bit2}  # Limit 2
      - {index: 0x6020, sub_index: 0x07, type: bool}  # Error
      - {index: 0x0000, sub_index: 0x00, type: bool}  # Gap
      - {index: 0x0000, sub_index: 0x00, type: bit5}  # Gap
      - {index: 0x6020, sub_index: 0x0e, type: bool}  # Sync error
      - {index: 0x6020, sub_index: 0x0f, type: bool}  # TxPDO State
      - {index: 0x6020, sub_index: 0x10, type: bool}  # TxPDO Toggle
      - {index: 0x6020, sub_index: 0x11, type: int16, state_interface: analog_input.3, factor: 0.000305185}
  - index: 0x1a06
    channels:
      - {index: 0x6030, sub_index: 0x01, type: bool}  # Underrange
      - {index: 0x6030, sub_index: 0x02, type: bool}  # Overrange
      - {index: 0x6030, sub_index: 0x03, type: bit2}  # Limit 1
      - {index: 0x6030, sub_index: 0x05, type: bit2}  # Limit 2
      - {index: 0x6030, sub_index: 0x07, type: bool}  # Error
      - {index: 0x0000, sub_index: 0x00, type: bool}  # Gap
      - {index: 0x0000, sub_index: 0x00, type: bit5}  # Gap
      - {index: 0x6030, sub_index: 0x0e, type: bool}  # Sync error
      - {index: 0x6030, sub_index: 0x0f, type: bool}  # TxPDO State
      - {index: 0x6030, sub_index: 0x10, type: bool}  # TxPDO Toggle
      - {index: 0x6030, sub_index: 0x11, type: int16, state_interface: analog_input.4, factor: 0.000305185}
sm:  # Sync Manager
  - {index: 3, type: input, pdo: tpdo, watchdog: enable}
