# Configuration file for Omron NX ECC201 with id5442
# Description : Omron EtherCAT Coupler NX_ECC201 with NX_ID5442 16-ch Digital Input module
vendor_id: 0x00000083
product_id: 0x00000083
rpdo: #RxPDO
  - index: 0x1604
    channels:
      - {index: 0x7022, sub_index: 0x01, type: uint16}
tpdo:  # TxPDO
  - index: 0x1bf8
    channels:
      - {index: 0x3003, sub_index: 0x04, type: bit128}
      - {index: 0x3006, sub_index: 0x04, type: bit128}
  - index: 0x1bff
    channels:
      - {index: 0x2002, sub_index: 0x01, type: uint8}
  - index: 0x1bf4
    channels:
      - {index: 0x0000, sub_index: 0x00, type: bit8}
  - index: 0x1a00
    channels:
      - {index: 0x6002, sub_index: 0x01, type: uint16, state_interface: d_input}
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: disable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}
